name: ML Pipeline Deployment

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:

  ephemeral-deploy:
    name: Ephemeral Feature Deploy
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/deploy-ml-pipeline.yml#deploy-template
    with:
      environment: feature-branch

  preprod-deploy:
    name: Preprod/Latest Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: []
    concurrency:
      group: preprod-prod-deploy
      cancel-in-progress: true
    uses: ./.github/workflows/deploy-ml-pipeline.yml#deploy-template
    with:
      environment: preprod

  prod-deploy:
    name: Production Deploy
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: []
    concurrency:
      group: preprod-prod-deploy
      cancel-in-progress: true
    uses: ./.github/workflows/deploy-ml-pipeline.yml#deploy-template
    with:
      environment: prod